### ISSUE TITLE
Vercel deployment

### ISSUE THREAD

**Issue by NostromoUS** [Namysh/candy-machine-mint-vue3#1]
Great job on this. Works and looks great in dev mode.

Any idea why deploying to vercel or netlify results in a blank page even though running locally works perfectly? Has it got anything to do with router fallback?

Cheers!

**Comment by Namysh** [comment]
The `publicPath` was set to `candy-machine-mint-vue3` to make it work with Github Pages Hosting. I updated it to ` `, it should work on Vercel and Netlify now

**Comment by NostromoUS** [comment]
Thank you. That was so obvious and yes it did work!

I noticed though, not sure if it's ok asking here that: import VueCountdown from '@chenfengyuan/vue-countdown';

Isn't being used, it's only declared in the template above the imports so the countdown doesn't really show. Not sure if you were aware. And again, great job on this!

**Comment by Namysh** [comment]
It is used in the template, it appears if the environment variable `VUE_APP_CANDY_START_DATE` is greater than today's date. 

But there might be some unnecessary stuff, I will eventually update this repository to make it more like a template and provide some documentation

**Comment by NostromoUS** [comment]
Hm. I see. The timestamp is definitely in the future, say like in an hour. It still shows the Mint button and no countdown for some reason though of course, the mint itself doesn't go through

**Comment by Namysh** [comment]
I commited a fix, it should works now (as long as there is no sold out)

**Comment by Occvlt21** [comment]
Thank you. I tried it and unfortunately it isn't working still. I don't know if this help but it does show that vuecountdown is declared but never used?

![image](https://user-images.githubusercontent.com/95923009/145632643-dd6f5352-fe68-447e-afe8-41f18d97b839.png)

**Comment by NostromoUS** [comment]
Cheers for looking into it! Though I don't think it's working? vscode does show that the value is declared but never read? Not sure if that helps!

![image](https://user-images.githubusercontent.com/95372495/145632867-9bae1989-0ab1-4bfe-9bdf-e853e6af030e.png)
