### ISSUE TITLE
Update for Candy Machine V2?

### ISSUE THREAD

**Issue by alvy1111** [Namysh/candy-machine-mint-vue3#3]
Hello, awesome job! It is very rare to see any VUE help on the candy machine. I am trying to rework this for the candy machine v2 program. I keep getting error message 0x138. Would you know what I can do to get a mint to push through? Any help is greatly appreciated!

**Comment by Namysh** [comment]
Hi, I updated it to a V2 but it's not comitted and ready to be. In order the rework it I used the new .ts files [here](https://github.com/metaplex-foundation/metaplex/tree/master/js/packages/candy-machine-ui/src) and kept the same Vue architecture (do not forget to support whitelist). 

There is a well-done Svelte implementation around here, I think it may be a good idea to check how it was done.

**Comment by Reouv** [comment]
Hi, You did awesome work on V1, Is there any update on your work for V2 ?

**Comment by Namysh** [comment]
Hi, no there is not
